-- liquibase formatted sql

-- changeset oalekseenko:1
CREATE TABLE animal (
                        id bigint generated by default as identity primary key,
                        "name" varchar(50) NOT NULL,

);


CREATE TABLE person (
                        id bigint generated by default as identity primary key,
                        "name" varchar(50) not null,
                        email varchar(50) not null,
                        phone varchar(20) not null,
                        address varchar(100) not null,
                        chat_id bigint not null,
                        animal_id bigint unique references animal(id),
                        animal_adopt_date date,
                        last_report_date date
);
CREATE TABLE report (
                        id bigint generated by default as identity primary key,
                        photo_path varchar not null,
                        photo_size int not null,
                        media_type varchar not null,
                        photo_data bytea not null,
                        description text not null,
                        report_date date not null,
                        person_id bigint not null references person(id)
);

-- changeset gabriel:1
CREATE TABLE animal_cat (
                        id bigint generated by default as identity primary key,
                        "name" varchar(50) NOT NULL,

);

CREATE TABLE person_cat (
                        id bigint generated by default as identity primary key,
                        "name" varchar(50) not null,
                        email varchar(50) not null,
                        phone varchar(20) not null,
                        address varchar(100) not null,
                        chat_id bigint not null,
                        animal_cat_id bigint unique references animal_cat(id),
                        animal_cat_adopt_date date,
                        last_report_cat_date date
);

CREATE TABLE report_cat (
                        id bigint generated by default as identity primary key,
                        photo_path varchar not null,
                        photo_size int not null,
                        media_type varchar not null,
                        photo_data bytea not null,
                        description text not null,
                        report_cat_date date not null,
                        person_cat_id bigint not null references person_cat(id)
);