-- liquibase formatted sql

-- changeset oalekseenko:1
CREATE TABLE person (
    id bigint generated by default as identity primary key,
    "name" varchar(50) not null,
    email varchar(50) not null,
    phone varchar(20) not null,
    address varchar(100) not null,
    chat_id bigint not null,
    animal_ig bigint -- todo: check how to create one-to-one connection with animal table
    animal_adopt_date date,
    last_report_date date,
    reports -- todo: check how to create one-to-many connection with report table
);

CREATE TABLE animal (
    id bigint generated by default as identity primary key,
    "name" varchar(50),
    person_id bigint -- todo check one-to-one connection to person table
);

CREATE TABLE report (

);